package studio.gnosticdeveloper.bonusbissen.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import studio.gnosticdeveloper.bonusbissen.dto.request.RewardCreateRequest;
import studio.gnosticdeveloper.bonusbissen.dto.request.RewardUpdateRequest;
import studio.gnosticdeveloper.bonusbissen.entity.Reward;
import studio.gnosticdeveloper.bonusbissen.exception.NotFoundException;
import studio.gnosticdeveloper.bonusbissen.repository.RewardRepository;

@Service
public class RewardService {

    private final RewardRepository rewardRepository;

    private static final long MAX_BYTES = 2 * 1024 * 1024; // 2MB
    // private static final int MAX_WIDTH = 1000;
    private static final Set<String> TYPES_ALLOWED = Set.of("image/jpeg", "image/png", "image/webp");

    @Value("${app.uploads.dir}")
    private String uploadsDir;

    public RewardService(RewardRepository rewardRepository) {
        this.rewardRepository = rewardRepository;
    }

    @Transactional(readOnly = true)
    public List<Reward> listActive(String search) {
        String term = search == null || search.isBlank() ? null : search.trim();
        return rewardRepository.findByActiveTrue(term);
    }

    @Transactional(readOnly = true)
    public Reward findById(UUID id) {
        return rewardRepository.findById(id).orElseThrow(() -> new NotFoundException("Reward not found: " + id));
    }

    // @Transactional(readOnly = true)
    // public List<TopRewardResponse> getTopRewards() {
    //     Pageable topTen = PageRequest.of(0, 10);
    //     return rewardRepository.getTopRewards(topTen);
    // }

    @Transactional
    public Reward create(RewardCreateRequest request) {
        String imagePath = null;

        if (request.image() != null && !request.image().isEmpty()) {
            try {
                imagePath = saveImage(request.image());
            } catch (IOException e) {
                // Note: we catch the exception so the app doesn't crash if the image can't be saved.
                // Personally, I prefer to keep it like this since if the image doesn't save, the app should still work.
                System.err.println("Error al guardar la imagen: " + e.getMessage());
            }
        }

        Reward reward = new Reward();
        reward.setTitle(request.title());
        reward.setDescription(request.description());
        reward.setCostPoints(request.costPoints());
        reward.setDiscountValue(request.discountValue());
        reward.setImagePath(imagePath);
        return rewardRepository.save(reward);
    }

    @Transactional
    public void delete(UUID id) {
        Reward reward = rewardRepository.findById(id).orElseThrow(() -> new NotFoundException("No se encontró la recompensa con id: " + id));
        reward.setActive(false);
        rewardRepository.save(reward);
    }

    private String saveImage(MultipartFile file) throws IOException {
        if (!TYPES_ALLOWED.contains(file.getContentType())) {
            throw new IllegalArgumentException("Tipo de archivo no permitido.");
        }
        if (file.getSize() > MAX_BYTES) {
            throw new IllegalArgumentException("La imagen supera el tamaño máximo de 2MB.");
        }

        // Filename generated by the server, to avoid collisions and path traversal
        String filename = UUID.randomUUID() + ".jpg";
        Path destino = Paths.get(uploadsDir, filename);
        Files.createDirectories(destino.getParent());

        // TODO: Implement file saving, with or without resizing the image.
        // Note: Thumbnails is not the only way to resize images, but it's a simple and effective solution for this use case.
        // We can simply save the file normally without using this library.
        // Thumbnails.of(file.getInputStream()).size(MAX_WIDTH, MAX_WIDTH).outputFormat("jpg").outputQuality(0.8).toFile(destino.toFile());

        return "rewards/" + filename;
    }

    @Transactional
    public Reward update(UUID id, RewardUpdateRequest request) {
        Reward reward = rewardRepository.findById(id).orElseThrow(() -> new NotFoundException("Reward not found: " + id));

        reward.setTitle(request.title());
        reward.setDescription(request.description());
        reward.setCostPoints(request.costPoints());
        reward.setDiscountValue(request.discountValue());

        String oldImagePath = reward.getImagePath();

        if (request.image() != null && !request.image().isEmpty()) {
            // Caso 2: imagen nueva. Guardamos primero, actualizamos la fila
            // después, borramos la vieja al final, en ese orden, para nunca
            // quedarnos sin ninguna imagen válida si algo falla a mitad de camino.
            try {
                String newImagePath = saveImage(request.image());
                reward.setImagePath(newImagePath);
                reward = rewardRepository.save(reward);
                deleteImageFile(oldImagePath);
            } catch (IOException e) {
                // Mismo criterio que en el alta: si la imagen no se pudo guardar,
                // la app sigue funcionando con el resto de los campos actualizados,
                // conservando la imagen anterior.
                System.err.println("Error al guardar la imagen: " + e.getMessage());
                reward = rewardRepository.save(reward);
            }
        } else if (request.removeImage()) {
            // Caso 3: sacar imagen sin poner otra.
            reward.setImagePath(null);
            reward = rewardRepository.save(reward);
            deleteImageFile(oldImagePath);
        } else {
            // Caso 1: no tocar la imagen. Ni un solo I/O de archivos acá.
            reward = rewardRepository.save(reward);
        }

        return reward;
    }

    private void deleteImageFile(String imagePath) {
        if (imagePath == null) return;
        try {
            // imagePath viene como "rewards/xxxx.jpg".
            Path filePath = Paths.get(uploadsDir, imagePath.replaceFirst("^rewards/", ""));
            Files.deleteIfExists(filePath);
        } catch (IOException e) {
            // No relanzamos: si el archivo viejo no se pudo borrar, es un
            // archivo huérfano en disco, molesto pero no corrompe datos. La
            // fila de la base ya quedó correcta en cualquiera de los dos
            // casos que llaman a este método.
            // Nota: un capo claudio codo.
            System.err.println("Error al borrar la imagen anterior: " + e.getMessage());
        }
    }
}
